app = "game-backlog-api"
primary_region = "ord"

[build]
  builder = "paketobuildpacks/builder:base"
  args = { RUBY_VERSION = "3.2.2" }

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

[deploy]
  release_command = "./bin/rails db:wait db:prepare"

[env]
  RAILS_ENV = "production"
  RAILS_LOG_TO_STDOUT = "true"

[vm]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
